name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Install Dependencies Linux
      if: runner.os == 'Linux'
      run: sudo apt-get -yq update && sudo apt-get -yq install cmake libsdl2-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavdevice-dev
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: release
        # Target architecture of the ffmpeg executable to install. Defaults to the
        # system architecture. Only x64 and arm64 are supported (arm64 only on Linux).
        architecture: 'x64'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Package
      if: github.ref != 'refs/heads/main'
      run: |
        cd build
        cpack

    - name: Publish
      if: github.ref != 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        artifactErrorsFailBuild: true
        prerelease: true
        removeArtifacts: true
        artifacts: "${{github.workspace}}/build/dist/*.*"
